/*
 * Nuki API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Contact: contact@nuki.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type OpenerIntercomModel struct {
	// The intercom ID
	IntercomId int32 `json:"intercomId"`
	// The related brand ID
	BrandId int32 `json:"brandId"`
	// The type of the model
	Type_ int32 `json:"type"`
	// The model name
	Model string `json:"model"`
	// Verified Nuki intercom: 1 .. verified to work, 2 .. may be compatible, but not verified, 3 .. not compatible
	Verified int32 `json:"verified"`
	// Connection for ground BUS
	ConGndBus string `json:"conGndBus"`
	// Connection for audio BUS
	ConBusAudio string `json:"conBusAudio"`
	// Connection for audio out
	ConAudioout string `json:"conAudioout"`
	// Connection for doorbell plus
	ConDoorbellPlus string `json:"conDoorbellPlus"`
	// Connection for doorbell minus
	ConDoorbellMinus string `json:"conDoorbellMinus"`
	// Connection for open the door
	ConOpendoor string `json:"conOpendoor"`
	// Connection for ground analogue
	ConGndAnalogue string `json:"conGndAnalogue"`
	// Settings value for BUS mode switch
	BusModeSwitch int32 `json:"busModeSwitch"`
	// Settings value for BUS mode switch short cicuit duration
	BusModeSwitchShortCircuitDuration int32 `json:"busModeSwitchShortCircuitDuration"`
	// The creation date
	CreationDate time.Time `json:"creationDate,omitempty"`
	// The update date
	UpdateDate time.Time `json:"updateDate,omitempty"`
}
