/*
 * Nuki API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Contact: contact@nuki.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AccountSubUpdate struct {
	// The new email address
	Email string `json:"email,omitempty"`
	// The new password (must be at least 5 chars long)
	Password string `json:"password,omitempty"`
	// The new name of the sub account
	Name string `json:"name,omitempty"`
	// The new right bitmask of the sub account: 1 .. operate smartlock, 2 .. change smartlock config, 4 .. manage smartlock users, 8 .. view smartlock logs, 16 .. manage sub accounts, 32 .. manage sub accounts, 64 .. create smartlocks
	Rights int32 `json:"rights,omitempty"`
	// The language code
	Language string `json:"language"`
	// The optional config
	Config *AccountConfig `json:"config,omitempty"`
	// The optional profile
	Profile *AccountProfile `json:"profile,omitempty"`
}
