/*
 * Nuki API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Contact: contact@nuki.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type SmartlockAdvancedConfig struct {
	// Timeout in seconds for lock ‘n’ go
	LngTimeout int32 `json:"lngTimeout,omitempty"`
	// The desired action, if the button is pressed once: 0 .. no action, 1 .. intelligent, 2 .. unlock, 3 .. lock, 4 .. unlatch, 5 .. lock 'n' go, 6 .. show status
	SingleButtonPressAction int32 `json:"singleButtonPressAction,omitempty"`
	// The desired action, if the button is pressed twice: 0 .. no action, 1 .. intelligent, 2 .. unlock, 3 .. lock, 4 .. unlatch, 5 .. lock 'n' go, 6 .. show status
	DoubleButtonPressAction int32 `json:"doubleButtonPressAction,omitempty"`
	// Flag that indicates if the automatic detection of the battery type is enabled
	AutomaticBatteryTypeDetection bool `json:"automaticBatteryTypeDetection,omitempty"`
	// Duration in seconds for holding the latch in unlatched position
	UnlatchDuration int32 `json:"unlatchDuration,omitempty"`
	// The operation id - if set it's locked for another operation
	OperationId string `json:"operationId,omitempty"`
	// The absolute total position in degrees that has been reached during calibration
	TotalDegrees int32 `json:"totalDegrees"`
	// Offset that alters the single locked position
	SingleLockedPositionOffsetDegrees int32 `json:"singleLockedPositionOffsetDegrees"`
	// Offset that alters the position where transition from unlocked to locked happens
	UnlockedToLockedTransitionOffsetDegrees int32 `json:"unlockedToLockedTransitionOffsetDegrees,omitempty"`
	// Offset that alters the unlocked position
	UnlockedPositionOffsetDegrees int32 `json:"unlockedPositionOffsetDegrees"`
	// Offset that alters the locked position
	LockedPositionOffsetDegrees int32 `json:"lockedPositionOffsetDegrees"`
	// Flag that indicates that the inner side of the used cylinder is detached from the outer side
	DetachedCylinder bool `json:"detachedCylinder,omitempty"`
	// The type of the batteries present in the smart lock: 0 .. alkali, 1 .. accumulator, 2 .. lithium
	BatteryType int32 `json:"batteryType"`
	// New separate flag with FW >= 2.7.8/1.9.1: The Auto Lock feature automatically locks your door when it has been unlocked for a certain period of time
	AutoLock bool `json:"autoLock,omitempty"`
	// Seconds until the smart lock relocks itself after it has been unlocked. FW < 2.7.8/1.9.1: No auto relock if value is 0, FW >= 2.7.8/1.9.1: has to be >=2 (defaults to 2 for values <2 if autoLock is set to true)
	AutoLockTimeout int32 `json:"autoLockTimeout,omitempty"`
	// Flag that indicates if available firmware updates for the deviceshould be installed automatically
	AutoUpdateEnabled bool `json:"autoUpdateEnabled,omitempty"`
}
