/*
 * Nuki API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Contact: contact@nuki.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type SmartlockSmartdoorAdvancedConfig struct {
	// Timeout in seconds for lock ‘n’ go
	LngTimeout int32 `json:"lngTimeout,omitempty"`
	// The desired action, if the button is pressed once: 0 .. no action, 1 .. intelligent, 2 .. unlock, 3 .. lock, 4 .. unlatch, 5 .. lock 'n' go, 6 .. show status
	SingleButtonPressAction int32 `json:"singleButtonPressAction,omitempty"`
	// The desired action, if the button is pressed twice: 0 .. no action, 1 .. intelligent, 2 .. unlock, 3 .. lock, 4 .. unlatch, 5 .. lock 'n' go, 6 .. show status
	DoubleButtonPressAction int32 `json:"doubleButtonPressAction,omitempty"`
	// Flag that indicates if the automatic detection of the battery type is enabled
	AutomaticBatteryTypeDetection bool `json:"automaticBatteryTypeDetection,omitempty"`
	// Duration in seconds for holding the latch in unlatched position
	UnlatchDuration int32 `json:"unlatchDuration,omitempty"`
	// The operation id - if set it's locked for another operation
	OperationId string `json:"operationId,omitempty"`
	// The volume of the buzzer: 0 .. off, 1 .. low, 2 .. normal
	BuzzerVolume int32 `json:"buzzerVolume,omitempty"`
	// Set of supported battery types: 0 .. alkali, 1 .. accumulator, 2 .. lithium, 3 .. fixed, 254 .. automatic, 255 .. unknown
	SupportedBatteryTypes []int32 `json:"supportedBatteryTypes,omitempty"`
	// The type of the batteries present in the smart lock: 0 .. alkali, 1 .. accumulator, 2 .. lithium, 3 .. fixed, 255 .. unknown
	BatteryType int32 `json:"batteryType"`
	// Seconds until the smart lock relocks itself after it has been unlocked. No auto relock if value is 0
	AutoLockTimeout int32 `json:"autoLockTimeout,omitempty"`
	// The Auto Lock feature automatically locks your door when it has been unlocked for a certain period of time
	AutoLock bool `json:"autoLock"`
}
