/*
 * Nuki API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Contact: contact@nuki.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type NotificationSetting struct {
	// The smartlock ID, if not set all Smart Locks of the account  are enabled for push notifications
	SmartlockId int64 `json:"smartlockId,omitempty"`
	// A set on which push notifications should be triggered: lock, unlock, unlatch, lockngo, open, ring, doorsensor, warnings, smartlock
	TriggerEvents []string `json:"triggerEvents"`
	// A set of auth IDs to filter push notifications to certain  users or keypads. If no entry push notifications are triggered for all users and keypads
	AuthIds []string `json:"authIds,omitempty"`
}
