/*
 * Nuki API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Contact: contact@nuki.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AddressTokenInfo struct {
	// The id
	Id string `json:"id"`
	// The address name
	AddressName string `json:"addressName"`
	// The associated smartlock names
	SmartlockNames []string `json:"smartlockNames"`
}
