/*
 * Nuki API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Contact: contact@nuki.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type OpenerIntercomBrand struct {
	// The brand ID
	BrandId int32 `json:"brandId"`
	// The brand name
	Brand string `json:"brand"`
}
