/*
 * Nuki API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Contact: contact@nuki.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AdvancedConfirmationResponse struct {
	// A UUID to identify the upcoming asynchronously web hook response
	RequestId string `json:"requestId"`
}
