/*
 * Nuki API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Contact: contact@nuki.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type SmartlockWebConfig struct {
	// True if a battery warning is send via email
	BatteryWarningPerMailEnabled bool `json:"batteryWarningPerMailEnabled,omitempty"`
}
