/*
 * Nuki API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Contact: contact@nuki.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type SmartlockLogOpenerLog struct {
	// Flag indicating if continuous mode was active
	ActiveCm bool `json:"activeCm"`
	// Flag indicating if ring to open was active
	ActiveRto bool `json:"activeRto"`
	// The cause of the activation of ring to open or continuous mode: 0 .. doorbell, 1 .. timecontrol, 2 .. app, 3 .. button, 4 .. fob, 5 .. bridge, 6 .. keypad
	Source int32 `json:"source"`
	// Flag indicating a geo fence induced action
	FlagGeoFence bool `json:"flagGeoFence"`
	// Flag indicating a force induced action
	FlagForce bool `json:"flagForce"`
	// Flag indicating if doorbell suppression was active
	FlagDoorbellSuppression bool `json:"flagDoorbellSuppression"`
}
