/*
 * Nuki API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Contact: contact@nuki.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AccountCreate struct {
	// The email address
	Email string `json:"email"`
	// The password (must be at least 5 chars long)
	Password string `json:"password"`
	// The name
	Name string `json:"name"`
	// The language code
	Language string `json:"language"`
	// The optional profile
	Profile *AccountProfile `json:"profile,omitempty"`
}
