/*
 * Nuki API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Contact: contact@nuki.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type AddressReservation struct {
	// The id
	Id string `json:"id"`
	// The address id
	AddressId int32 `json:"addressId"`
	// The account id
	AccountId int32 `json:"accountId"`
	// The email of the guest
	Email string `json:"email"`
	// The name of the guest
	Name string `json:"name"`
	// The number of guests
	Guests int32 `json:"guests"`
	// The number of guests issued
	GuestsIssued int32 `json:"guestsIssued"`
	// True if a keypad authorization was issued
	KeypadIssued bool `json:"keypadIssued"`
	// The state
	State string `json:"state"`
	// The optional service id if the address is from an partner service
	ServiceId string `json:"serviceId,omitempty"`
	// The reference (booking code)
	Reference string `json:"reference,omitempty"`
	// The automation state
	Automation int32 `json:"automation"`
	// True if the user has checked in, false if the check in is pending, null if it isn't monitored
	CheckedIn bool `json:"checkedIn,omitempty"`
	// The start date
	StartDate time.Time `json:"startDate"`
	// The end date
	EndDate time.Time `json:"endDate"`
	// The update date
	UpdateDate time.Time `json:"updateDate"`
}
