/*
 * Nuki API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Contact: contact@nuki.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type SmartlockCreate struct {
	// The smartlock id in 32 bits (only for a smartlock, opener or smartdoor)
	SmartlockId int32 `json:"smartlockId,omitempty"`
	// The type: 0 .. smartlock, 1 .. box, 2 .. opener, 3 .. smartdoor
	Type_ int32 `json:"type"`
	// The name
	Name string `json:"name"`
	// The authorization uuid (only for a smartlock, opener or smartdoor)
	AuthUuid string `json:"authUuid,omitempty"`
	// The authorization id (boxId if box)
	AuthId int32 `json:"authId"`
	// The authorization secret
	AuthSecret string `json:"authSecret"`
}
