/*
 * Nuki API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Contact: contact@nuki.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type AccountUser struct {
	// The account user id
	AccountUserId int32 `json:"accountUserId"`
	// The account id
	AccountId int32 `json:"accountId"`
	// The optional type: 0 .. user, 1 .. company
	Type_ int32 `json:"type,omitempty"`
	// The email address
	Email string `json:"email"`
	// The name
	Name string `json:"name"`
	// The language code
	Language string `json:"language,omitempty"`
	// The operation id - if set it's locked for another operation
	OperationId string `json:"operationId,omitempty"`
	// The creation date
	CreationDate time.Time `json:"creationDate"`
	// The update date
	UpdateDate time.Time `json:"updateDate"`
}
