/*
 * Nuki API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Contact: contact@nuki.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type SmartlockLog struct {
	// The unique id for the smartlock log
	Id string `json:"id"`
	// The smartlock id
	SmartlockId int64 `json:"smartlockId"`
	// The device type: 0 .. smartlock and box, 2 .. opener, 3 .. smartdoor
	DeviceType int32 `json:"deviceType"`
	// The id of the linked account user
	AccountUserId int32 `json:"accountUserId,omitempty"`
	// The id of the linked smartlock auth
	AuthId string `json:"authId,omitempty"`
	// The name
	Name string `json:"name"`
	// The action: 1 .. unlock, 2 .. lock, 3 .. unlatch, 4 .. lock'n'go, 5 .. lock'n'go with unlatch, 208 .. door warning ajar, 209 door warning status mismatch, 224 .. doorbell recognition (only Opener), 240 .. door opened, 241 .. door closed, 242 .. door sensor jammed, 243 .. firmware update, 250 .. door log enabled, 251 .. door log disabled, 252 .. initialization, 253 .. calibration, 254 .. log enabled, 255 .. log disabled
	Action int32 `json:"action"`
	// The trigger: 0 .. system, 1 .. manual, 2 .. button, 3 .. automatic, 4 .. web, 5 .. app, 6 .. auto lock, 7 .. accessory, 255 .. keypad
	Trigger int32 `json:"trigger"`
	// The completion state: 0 .. Success, 1 .. Motor blocked, 2 .. Canceled, 3 .. Too recent, 4 .. Busy, 5 .. Low motor voltage, 6 .. Clutch failure, 7 .. Motor power failure, 8 .. Incomplete, 9 .. Rejected, 10 .. Rejected night mode, 254 .. Other error, 255 .. Unknown error
	State int32 `json:"state"`
	// True if it was an auto unlock
	AutoUnlock bool `json:"autoUnlock"`
	// The log date
	Date time.Time `json:"date"`
	// The opener specific log
	OpenerLog *SmartlockLogOpenerLog `json:"openerLog,omitempty"`
	// The door sensor warning ajar timeout (in minutes, only for action = 208)
	AjarTimeout int32 `json:"ajarTimeout,omitempty"`
}
