/*
 * Nuki API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Contact: contact@nuki.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AdvancedApiKeyUpdate struct {
	// The URL where our webhooks should point to
	WebhookUrl string `json:"webhookUrl"`
	// The features to trigger webhooks, for all types except 'ONLY_SECRET'
	WebhookFeatures []string `json:"webhookFeatures"`
}
