/*
 * Nuki API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Contact: contact@nuki.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AccountUserCreate struct {
	// The optional type - only allowed for caretakers: 0 .. user, 1 .. company
	Type_ int32 `json:"type,omitempty"`
	// The email address
	Email string `json:"email"`
	// The name
	Name string `json:"name"`
	// The language code
	Language string `json:"language,omitempty"`
}
