/*
 * Nuki API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Contact: contact@nuki.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type Notification struct {
	// The unique notificationId for the notification
	NotificationId string `json:"notificationId"`
	// The reference ID, an ID to identify a foreign system
	ReferenceId string `json:"referenceId,omitempty"`
	// The push ID or the POST URL for a webhook
	PushId string `json:"pushId"`
	// The 40 byte hex string to sign the checksumof the POST payload if the notification is webhook (os=2)
	Secret string `json:"secret,omitempty"`
	// The operating system: 0 .. Android, 1 .. iOS, 2 .. web hook
	Os int32 `json:"os"`
	// The language of push messages: cs, de, en (default), es, fr, it, nl, sk
	Language string `json:"language,omitempty"`
	// Current state: 0 .. init, 1 .. active, 2 .. failed
	Status int32 `json:"status,omitempty"`
	// The last active date
	LastActiveDate time.Time `json:"lastActiveDate,omitempty"`
	// Settings per Smart Lock
	Settings []NotificationSetting `json:"settings"`
}
