/*
 * Nuki API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Contact: contact@nuki.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type ApiKeyToken struct {
	// The id
	Id string `json:"id"`
	// The account id
	AccountId int32 `json:"accountId"`
	// The description
	Description string `json:"description,omitempty"`
	// The access token
	AccessToken string `json:"accessToken,omitempty"`
	// The list of scopes
	Scopes []string `json:"scopes"`
	// The creation date
	CreationDate time.Time `json:"creationDate"`
}
