/*
 * Nuki API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Contact: contact@nuki.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AccountSettingWeb struct {
	// The initial view type of the device page
	DeviceViewType string `json:"deviceViewType,omitempty"`
	// The initial sort type of the device page
	DeviceSortType string `json:"deviceSortType,omitempty"`
	// If true, Nuki Club info is dismissed and no banner is shown
	NukiClubDismissed bool `json:"nukiClubDismissed,omitempty"`
}
