/*
 * Nuki API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Contact: contact@nuki.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type AccountConfig struct {
	// The alexa pin - used by alexa for unlock actions
	AlexaPin string `json:"alexaPin"`
	// The google smart home pin - used for unlock actions
	GactionsHomePin string `json:"gactionsHomePin"`
	// The opt enabled date
	OtpEnabledDate time.Time `json:"otpEnabledDate,omitempty"`
}
