/*
 * Nuki API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Contact: contact@nuki.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type SmartlockAuth struct {
	// The unique id for the smartlock authorization
	Id string `json:"id"`
	// The smartlock id
	SmartlockId int64 `json:"smartlockId"`
	// The id of the linked account user
	AccountUserId int32 `json:"accountUserId,omitempty"`
	// The smartlock authorization id
	AuthId int32 `json:"authId,omitempty"`
	// The keypad code (only for type keypad)
	Code int32 `json:"code,omitempty"`
	// The type of the authorization: 0 .. app, 1 .. bridge, 2 .. fob, 3 .. keypad, 13 .. keypad code, 14 .. z-key, 15 .. virtual
	Type_ int32 `json:"type"`
	// The name of the authorization (max 32 chars)
	Name string `json:"name"`
	// True if the auth is enabled
	Enabled bool `json:"enabled"`
	// True if the auth has remote access
	RemoteAllowed bool `json:"remoteAllowed"`
	// The lock count
	LockCount int32 `json:"lockCount"`
	// The allowed from date
	AllowedFromDate time.Time `json:"allowedFromDate,omitempty"`
	// The allowed until date
	AllowedUntilDate time.Time `json:"allowedUntilDate,omitempty"`
	// The allowed weekdays bitmask: 64 .. monday, 32 .. tuesday, 16 .. wednesday, 8 .. thursday, 4 .. friday, 2 .. saturday, 1 .. sunday
	AllowedWeekDays int32 `json:"allowedWeekDays,omitempty"`
	// The allowed from time (in minutes from midnight)
	AllowedFromTime int32 `json:"allowedFromTime,omitempty"`
	// The allowed until time (in minutes from midnight)
	AllowedUntilTime int32 `json:"allowedUntilTime,omitempty"`
	// The last active date
	LastActiveDate time.Time `json:"lastActiveDate,omitempty"`
	// The creation date
	CreationDate time.Time `json:"creationDate,omitempty"`
	// The update date
	UpdateDate time.Time `json:"updateDate,omitempty"`
	// The operation id - if set the auth is locked for another operations.
	OperationId *ObjectId `json:"operationId,omitempty"`
}
