/*
 * Nuki API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Contact: contact@nuki.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type ApiKey struct {
	// The id
	ApiKeyId int32 `json:"apiKeyId"`
	// The account id
	AccountId int32 `json:"accountId"`
	// The description
	Description string `json:"description,omitempty"`
	// The redirect uris
	RedirectUris []string `json:"redirectUris,omitempty"`
	// The creation date
	CreationDate time.Time `json:"creationDate"`
	// The api key
	ApiKey string `json:"apiKey,omitempty"`
}
