/*
 * Nuki API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Contact: contact@nuki.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AccountProfile struct {
	// The first name
	FirstName string `json:"firstName"`
	// The last name
	LastName string `json:"lastName"`
	// The address
	Address string `json:"address"`
	// The postal code
	Zip string `json:"zip"`
	// The city
	City string `json:"city"`
	// The 2-letter country code
	Country string `json:"country"`
}
