/*
 * Nuki API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Contact: contact@nuki.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type MyAccount struct {
	// The account id
	AccountId int32 `json:"accountId"`
	// The type: 0 .. user, 1 .. company, 2 .. caretaker
	Type_ int32 `json:"type"`
	// The email address
	Email string `json:"email"`
	// The name
	Name string `json:"name"`
	// The master account id if it's a sub account
	MasterAccountId int32 `json:"masterAccountId,omitempty"`
	// The rights bitmask if it's a sub account: 1 .. manage smartlock, 2 .. operate smartlock, 4 .. manage smartlock config, 8 .. manage smartlock authorizations, 16 .. view smartlock logs, 32 .. manage sub accounts, 64 .. create smartlocks
	Rights int32 `json:"rights,omitempty"`
	// The language code
	Language string `json:"language,omitempty"`
	// The optional config
	Config *AccountConfig `json:"config,omitempty"`
	// The optional profile
	Profile *AccountProfile `json:"profile,omitempty"`
	// The secret base64 encoded
	Secret []string `json:"secret,omitempty"`
	// The creation date
	CreationDate time.Time `json:"creationDate"`
	// The update date
	UpdateDate time.Time `json:"updateDate"`
}
