/*
 * Nuki API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Contact: contact@nuki.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AccountUserUpdate struct {
	// The new email address
	Email string `json:"email,omitempty"`
	// The new name of the sub account
	Name string `json:"name,omitempty"`
	// The new language code
	Language string `json:"language,omitempty"`
}
