/*
 * Nuki API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Contact: contact@nuki.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type Address struct {
	// The address id
	AddressId int32 `json:"addressId"`
	// The account id
	AccountId int32 `json:"accountId"`
	// The name of the address
	Name string `json:"name"`
	// The smartlocks for this address
	SmartlockIds []int64 `json:"smartlockIds"`
	// The optional service id if the address is from an partner service
	ServiceId string `json:"serviceId,omitempty"`
	// The timezone
	TimeZone string `json:"timeZone,omitempty"`
	// The optional check in time (minutes of the day)
	CheckInTime int32 `json:"checkInTime,omitempty"`
	// The optional check out time (minutes of the day)
	CheckOutTime int32 `json:"checkOutTime,omitempty"`
	// The optional settings object
	Settings map[string]interface{} `json:"settings,omitempty"`
	// The creation date
	CreationDate time.Time `json:"creationDate"`
	// The update date
	UpdateDate time.Time `json:"updateDate"`
}
