/*
 * Nuki API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Contact: contact@nuki.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AccountSubCreate struct {
	// The email address
	Email string `json:"email"`
	// The password (must be at least 5 chars long)
	Password string `json:"password"`
	// The name of the sub account
	Name string `json:"name"`
	// The right bitmask of the sub account: 1 .. operate smartlock, 2 .. change smartlock config, 4 .. manage smartlock users, 8 .. view smartlock logs, 16 .. manage sub accounts
	Rights int32 `json:"rights"`
	// The language code
	Language string `json:"language"`
	// The optional profile
	Profile *AccountProfile `json:"profile,omitempty"`
}
