/*
 * Nuki API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Contact: contact@nuki.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type AddressToken struct {
	// The id
	Id string `json:"id"`
	// The address id
	AddressId int32 `json:"addressId"`
	// The creation date
	CreationDate time.Time `json:"creationDate"`
	// The redeem date
	RedeemDate time.Time `json:"redeemDate"`
	// The redeem account id
	RedeemAccountId int32 `json:"redeemAccountId"`
	// The list of invite keys
	InviteKeys []string `json:"inviteKeys,omitempty"`
	// The redeem result
	RedeemResult string `json:"redeemResult,omitempty"`
}
